### ISSUE TITLE
react-instantsearch release 🔙🔛🔝🔜

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1312]
Here are the necessary things to fix before we can claim a release. **Put your name next to one you wanna do**. Create an issue if necessary, otherwise just do it.

## API

We are getting there, nothing much left.

- [x] connectHitsPerPage must provide isRefined in items data
- [x] connectHitsPerPage must disallow configuring with only numbers (HitsPerPage items=[10,20,30]). We should always force using the object form. For consistency and single way to do one thing.
- [x] **(Marie)** rename InstantsSearch prop `state` to `searchState` 
- [x] Finish new awesome highlighting #1645 @bobylito 
- [x] release last beta version, update website @vvo
- [ ] Tune CSS API, add default font, style highlight #1683 
- [ ] Add specific Algolia user agent to distinguish instantsearch.js and react-instantsearch (see https://github.com/algolia/instantsearch.js/blob/f4c52d1716255f5721e4d6b6fb03995914651b33/src/lib/InstantSearch.js#L76)

## Website

- [ ] Implement landing design #1606 @LukyVj 
- [ ] ensure marketing tags are set
- [x] add docsearch @mthuret 
- [ ] headers highlighting seems again broken on left nav in getting started

## Docs

Docs must be 100% accurate, clear and to the point. We have some areas to fix.

- [ ] add docsearch
- [ ] Left sidebar is behaving badly #1671 
- [x] Ensure react-instantsearch website always link to the v2 branch as for viewing code
- [x] Ensure relative links are always working when website deployed to production (/instantsearch.js/react) #1639 @vvo
- [ ] Ensure we inject and use the version of react-instantsearch react-instantsearch-theme-algolia in the website so that links to specific versions are always up to date (like the CSS file) #1641 
- [x] **(Marie)** Ensure places we speak about "Component(s)" in the documentation are relevant. Otherwise it should be Widget (i.e. NO SearchBox component, YES SearchBox widget). Only `<InstantSearch>` can be called a component. Widgets are connected components. 
- [x] **(Marie)** getProvidedProps(props, state, search, meta) should always be getProvidedProps(props, searchState, searchResults, metadata). We need to be very precise about what we talk. Both code and documentation should always refer to searchState instead of InstantSearch state or state. It should be less confusing for users to always have a clear name to use.
- [ ] Ensure every connector has a precise documentation, in particular on currentRefinement and refine descriptions. We sometime have vague descriptions or erroneous ones, we need to be precise. (example: connectSearchBox). If we have a refine method, we need to explain how to call it, what are the argument. Maybe we could just add one example per connector (very very simple one), and put it at the top. One simple example speaks a lot more for connectors maybe than the vague props.
- [ ] Read, re-read every documentation as if you were a new user. Start from getting started, do it, read the guide, follow it, read API descriptions. This takes time but will be worth it.
- [ ] Everywhere we speak about an actual token to be used in JSX (Like the "InstantSearch component"), we should write it as JSX, like the "`<InstantSearch>` component". For ease of reading.
- [x] @vvo Ask a native english speaker to proof read the documentation once last beta is released
- [ ] Actually release the non beta version, right before we go live

Right after release:
- [ ] Announce react-instantsearch on instantsearch.js main README (develop branch)
  Link to the website, link to the code, top of the file. GOAL: be transparent
- [ ] Put a banner (need a banner, cc @sebnvzt) on instantsearch.js website
- [ ] Put a banner on Algolia.com website, or at least find a place where mentioning react-instantsearch makes sense and helps users

**Comment by vvo** [comment]
Wait it's not even finished.

**Comment by mthuret** [comment]
Maybe we should add : write some integration tests using our demos ?

**Comment by vvo** [comment]
> Maybe we should add : write some integration tests using our demos ?

Yep we would need those, but maybe not for the release. We released instantsearch.js V1 without any integration tests, they came six months later and it was OK.

No matter what, we already know exactly how to integrate them: https://github.com/algolia/instantsearch.js/tree/develop/functional-tests

**Comment by andymac4182** [comment]
Any idea how far off this is? We are starting a new react project and were hoping to integrate search throughout the app.

**Comment by vvo** [comment]
@andymac4182 The API changes should not be that hard to backport so I would suggest you to try the alpha, give feedback and iterate. We will clearly explain how to change your code when new API changes comes.

**Comment by joelm10** [comment]
Hi, is there plans to introduce Redux for state management in this release, or will it be a future one?
to allow switching between indexes, dynamically switching facets/disjunctive facets/config etc?

**Comment by joelm10** [comment]
also, i'd like to try out the alpha when ready

**Comment by bobylito** [comment]
@joelm10 

You can already use it right now :) https://www.npmjs.com/package/react-instantsearch We'd love to hear your feedback :)

What do you mean by using Redux? Do you want to store the state in a redux store?

**Comment by joelm10** [comment]
@bobylito cheers, i'll have a closer look over that.
I've been looking into portions of that for a while now- but didnt realise it was alpha.
Re Redux- in short yes. as a mechansim to keep track of config/which index to connect to and other dynamic switchable values.
While i could do this at component level, i'd prefer to have it at a higher level, which can be used to cascade down.

**Comment by vvo** [comment]
@joelm10 have a look at https://community.algolia.com/instantsearch.js/react/InstantSearch.html#controlled-state this is where you could plug redux I guess.

Try it, open new issues (this one is only for release tracking), come to gitter https://gitter.im/algolia/instantsearch.js

**Comment by vvo** [comment]
@joelm10 @andymac4182 Can you email me at vincent@algolia.com, so that I put you on the release news for this library? Thanks

**Comment by vvo** [comment]
Locking this, we are using it as a single point of entry for any work related on react-instantsearch. You can still open discussion here or privately.

**Comment by vvo** [comment]
:fire:
