### ISSUE TITLE
Unit test React.js components and the library

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#16]
# TODO:
- [x] setup the testing stack
- [x] write Template test
- [x] write lib/InstantSearch.js test
- [ ] write components/RefinementList.js (clic event use case)
- [x] write widget test

**Comment by vvo** [comment]
closing, we already have #227
