### ISSUE TITLE
instantsearch.js - v2 roadmap to release

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2072]
High level issue centralizing the progress of the implementation of instantsearch.js v2.

Connector:
- [x] Remove clearAll position from connector @bobylito 
- [x] TemplateProps hierarchicalMenu
- [x] Discuss the  tility of checking the rendering function
- [x] Expose connectors @iam4x
- [x] Make the widget pass all the options to the rendering as a black box @iam4x 
- [x] Ensure "items" connectors consistency (currentRefinement, refine, items[{isRefined, value, name}]) @iam4x
- [x] Nested template options and transform data, remove? / items clear currentRefinedValues
- [x] Make sure every widget rendering gets the instantseach instance @bobylito
- [x] Remove `container` / `DOM` references into connectors tests @iam4x
- [x] Remove the need of `attributeNameKey` in connectHierarchicalMenu @iam4x

V2:
 - [x] JSDoc of connectors/widgets
 - [x] Generate doc website
 - [x] drop react completly for oustide users @iam4x
 - [x] Change the default sort order (like #1529 but keeping the ability to override) @iam4x

Related issues:
 - Connectors #1923 

Dogfooding connectors (tested custom components): 
 - [x] connectMenu

**Comment by bobylito** [comment]
V2 is released!
