### ISSUE TITLE
[Meta] Add guides

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2640]
This issue reference all the missing guides of InstantSearch.js.

 - [ ] how to add default / unclearable search parameters (see #1357)
 - [x] using the URL Sync API (see #2636 and #2216, we should do it with the new API)
 - [x] how to use query rules with InstantSearch.js (see #2328)
 - [ ] how to manipulate the search parameters when not using widgets (see https://github.com/algolia/instantsearch.js/issues/2080)

Also see the issues referenced by the [Doc: guide](https://github.com/algolia/instantsearch.js/labels/Doc%3A%20guide) label.

**Comment by Haroenv** [comment]
these guides have been added since
