### ISSUE TITLE
New widget: hitsPerPageSelector

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#331]
Based on discussion in #317. We would need a widget in the same vein as the `indexSelector` that will let the us change the number of results displayed.

![image](https://cloud.githubusercontent.com/assets/283419/10664972/ef7f13c4-78c7-11e5-9761-75c94cdf5280.png)

Would have the same API as the `indexSelector`, but instead of passing a list of `indices`, we'll pass a list of `hitsPerPage` (if you have a better naming, shoot).

## API

```js
search.addWidget(
  instantsearch.widgets.hitsPerPageSelector({
    container: '#hits-per-page-selector',
    options: [
      {value: 10, label: '10 results'},
      {value: 50, label: '50 results'},
      {value: 100, label: '100 results'},
    ]
  })
);
```
No template to pass, BEM styling added to the `select` and `option`s.

## TODO

- [ ] Find a better name than `hitsPerPageSelector`
- [x] Find a better name than `hitsPerPage` attribute (`options`)
- [ ] Update doc to warn than displaying 1000 items is a bad idea

**Comment by redox** [comment]
:+1: @pixelastic 

If we keep the `hits` widget, I'm happy with the `hitsPerPageSelector` naming. No idea regarding the configuration attribute, looks not that bad. POV: go!

**Comment by vvo** [comment]
WFM, very nice :)

**Comment by vvo** [comment]
What about
```js
search.addWidget(
  instantsearch.widgets.hitsPerPageSelector({
    container: '#hits-per-page-selector',
    options: [
      {value: 10, label: '10 results'},
      {value: 50, label: '50 results'},
      {value: 100, label: '100 results'},
    ]
  })
);
```

This would map `<select><option></option></select>` and avoid repeating `hitsPerPage`.

**Comment by pixelastic** [comment]
I like `options` like you suggest. I'd go with that.

(Updating the main comment)
