### ISSUE TITLE
Allow building react custom based widgets

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#373]
# TODO:

- [ ] declare react and react-dom as peer dependencies and externals (careful about versioning)
- [ ] build instantsearch.js (react, react dom exposed)
- [ ] build instantsearch.noreact.js (no react, react dom), expose this as main build in package.json
- [ ] update documentation for npm users

This will allow us and our users to build react based widgets without any issue, much like jquery ones.

**Comment by pixelastic** [comment]
_What is the status of this discussion? I did not get which part is outdated._

This are very valid points, especially the one about hiding/not hiding that we are based on React and whet it implies for the visibility of React inside instantsearch. I have no answer to that right now, I'll have to think about it.

**Comment by vvo** [comment]
Sorry @pixelastic, I removed the outdated text I had put.

**Comment by bobylito** [comment]
What about having react and react-dom in the instantsearch namespace?

**Comment by vvo** [comment]
So I tried that @bobylito but then when you build custom react widgets and want to publish them as jsdelivr `<script>` (because you do not want to limit your widgets to a public that is only browserify/webpack) that's an issue.

For us, we can rely on some "DI" by reusing the instantsearch.deps.* in widgets but then if your custom widget wants to reuse any existing react component (say react-google-maps) then it will fail because we are not be able to inject "OUR" react into their component.

The underlying reused component (google-maps) will just try to require("react") which will fail.
