### ISSUE TITLE
1.0.0 release "right-track"

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#492]
I triaged the critical issues that I think are needed for a 1.0.0 release: **code and documentation wise**.

Project global view is on asana and contains more tasks, check it out.

You can see the issues on the waffle board: https://waffle.io/algolia/instantsearch.js?milestone=1.0.0

Have any other critical code/documentation issue? Put it here. I will keep the list updated.

If you do not agree with some of the issues, talk about it in another issue to keep this one clean.

Let's stay focused and only do what's here, no more time for small chores/tests.

We will determine the `next` roadmap once we release 1.0.0.

![giphy 13](https://cloud.githubusercontent.com/assets/123822/11009639/e747896c-84d8-11e5-853c-a0effbd62498.gif)

**Comment by pixelastic** [comment]
I've added #504 and #505.

I think https://github.com/algolia/instantsearch.js/issues/506 should also go into the list

**Comment by redox** [comment]
I've added #558 (required for the Amazon & youtube examples)

**Comment by pixelastic** [comment]
We need to freeze

**Comment by redox** [comment]
> We need to freeze

Sure, but those 2 ones are mandatory to build our examples. I prefer adding them now, especially because it was a <2-hour work.

**Comment by Shipow** [comment]
who's working on amazon?

**Comment by redox** [comment]
> who's working on amazon?

No one yet, do you want to give it a try? Otherwise it's on my todo list on the next 2 days :)

**Comment by Shipow** [comment]
Yes, I have to :)

**Comment by Shipow** [comment]
I'm also taking car of the example page upgrade.

**Comment by pixelastic** [comment]
@redox: I misclicked on my previous comment. I started writing that and then saw that it was required for the airbnb/youtube examples. I wanted to cancel and instead clicked the "close and comment"

But even if it is a 2h work, I believe we still need to discuss the API before rushing to the PR.

**Comment by redox** [comment]
> But even if it is a 2h work, I believe we still need to discuss the API before rushing to the PR.

I pushed the PR with the "question+do_not_merge" labels, I think it's the good compromise between agility & productivity :)

**Comment by vvo** [comment]
Cleaned the issue, removing what was done.

For reference at the time of this comment, this is done:

- [x] #245 documentation: warn to not use too many hierarchical levels for UX
- [x] #395 documentation: add usage to slider
- [x] #396 documentation: check usages of all widgets
- [x] #491 documentation: update widget jsdoc on release.sh
- [x] #472 documentation: unusable on mobile
- [x] #473 documentation: missing default values in jsdoc
- [x] #498 documentation: back button is not working
- [x] #505  documentation: priceRanges example has two "View HTML" buttons
- [x] #507 documentation: rendering of hierarchicalMenu is not correctly indented
- [x] #499 bug: no error when instantiating an unkown widget
- [x] #500 bug: css classes are doubled in pagination
- [x] #502 documentation: add note on automatic rangeSlider min max computation
- [x] #503 documentation/bug: css debug do not highlight label tag of checkbox
- [x] #520 documentation/bug: menu text overlaps main text
- [x] #522 documentation: slider not displaying well in airbnb example
- [x] #524 documentation: glitch when menu over white background
- [x] #528 documentation: the Template part of the page is cut

**Comment by vvo** [comment]
Done:
- [x] #156 documentation: add algolia requirements for every widget
- [x] #590 rename facetName to attributeName
- [x] #563 new widget: numericSelector
- [x] #488 `<script>` jQuery custom widget boilerplate
- [x] #585 hierarchicalMenu: limit not working
- [x] #504  documentation: Empty hitsPerPageSelector default value
- [x] #575 widget.init interface not consistent with widget.render

**Comment by pixelastic** [comment]
Regarding #576, I could use some help. I've been testing on iPhone 6 and Android 4.4 (still need a few tests) the main page as well as the documentation one.

I still did not touched the IE side of testing, nor the youtube/airbnb/amazon testing

**Comment by vvo** [comment]
Ok @pixelastic lets fix all the browser related issues tomorrow morning

**Comment by vvo** [comment]
annnnnnd we're done.

![giphy 15](https://cloud.githubusercontent.com/assets/123822/11246851/cb27f39e-8e19-11e5-8981-1baae7543ded.gif)
