### ISSUE TITLE
1.3 roadmap

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#820]
This is a living roadmap of the 1.3 release, please comment

## Features
- [x] implement a query hook #817
~~- [ ] add `hasChildren` template data to the hierarchical item template #818~~ canceled, need more work
- [x] menu widget should implement showMore #815 (released as 1.2.2, should have been in 1.2.0)

## Bugs
- [x] searchBox value should be updated when query updated programatically from the helper #729 
- [ ] searchBox should be cleared when reset button present and pressed #804 
- [x] base attribute not playing well with url sync #790

## Tests
- [ ] full functional test suite #814
- [ ] unit test url sync #243 
- [ ] unit test menu #237 

## Docs
- [x] precise default theme specifics #819
- [x] md5 documentation assets to avoid caching issues #816
