### ISSUE TITLE
Add a new widget to change the template to display hits

### ISSUE THREAD

**Issue by gregquat** [algolia/instantsearch.js#845]
I'd need a new widget to change the template used to display hits on the page.

Small parenthesis, for now, I made a custom system, but I encounter an issue with the "**currentRefinedValues**" widget.
To change the mode of displayal, I change the template in the "**hits**" widget, and I call a `search.start();`

This works well, but after a "clear filter", when I call the `search.start();`, some facets are reappearing in the "**currentRefinedValues**" widget (as if they were still in the object memory).

As this feature could be usefull to someone else, I prefer suggest to add the widget instead of correcting a very specific bug. 
End of the parenthesis.

The expected result could be something like this : 

![capture du 2016-02-15 15 17 56](https://cloud.githubusercontent.com/assets/293127/13051181/14feba06-d3f8-11e5-870a-d45632175f1f.png)

# API

```
search.addWidget(
  instantsearch.widgets.hitsDisplayMode({
    container: '#hits-display-mode',
    templates: {
      small: '<article>Hit {{objectID}}</article>',
      medium: '<article><strong>Hit {{objectID}}</strong>: {{{_highlightResult.name.value}}}</article>',
      full: '<article><h2>Hit {{objectID}}</h2> {{{_highlightResult.name.value}}}</article>'
    },
    default: 'medium',
    cssClasses: {
        active: 'active',
        iconSmall :'fa-th',
        iconMedium :'fa-bars',
        iconFull :'fa-th-large',
        small: 'small',
        medium: 'medium',
        full: 'full'
    }
  })
);
```

The requirements will be the small, medium and full template. Maybe we could use the template specified in "**hits**" as the medium one, I don't know.
We could also specify css classes, and the default template to apply (but this would be in conflict with the "**hits**" widget again, as they are complementary )

The rended html could be something like this :

```
<div class="hits-display-mode">
    <a href="#" class="small">
        <i class="fa fa-th"></i>
    </a>
    <a href="#" class="medium active">
        <i class="fa fa-bars"></i>
    </a>
    <a href="#" class="full">
        <i class="fa fa-th-large"></i>
    </a>
</div>
```

# TODO

- [ ] find a cool name for the widget
- [ ] determine the better way to do that without conflicting with the "hits" widget
- [ ] affine the customizable options (css, templating)

Thanks a lot

**Comment by vvo** [comment]
Hi, nice feedback!

Indeed what we would need here is maybe this: https://github.com/algolia/instantsearch.js/issues/753#issuecomment-168701879

- A way to update the configuration of a widget
- A way to force a render of the interface or a render of a specific widget

Both are not so easy to do for now but ultimately this is what we would need. See https://github.com/algolia/instantsearch.js/issues/852

As for your widget that's a very good one indeed, it would be great to have it as a community widget!

We will try to discuss those features soon, in the meantime you can comment on it and give us your feedback

**Comment by gregquat** [comment]
Hi,

Thanks. Indeed, if I can force the renderer, that would do the trick.

I'm trying to work on it but I'm not very familiar with React, so it can be long to have a good result ;)
I'm gonna watch the issues, I'll tell you if I have something to push.

**Comment by vvo** [comment]
@gregquat in instantsearch.js V2 we are planning to let you do the whole hit rendering yourself (say, with jQuery) along with being able to force a render.

Thanks!

Moved to #1071 (somehow)
